### ISSUE TITLE
sqlutil.get problem with SELECT   *   FROM     allwise.main LIMIT 10

### ISSUE THREAD

**Issue by richardgmcmahon** [segasai/astrolibpy#5]
using the current version of astrolibpy

query = """
SELECT
    *
FROM
    allwise.main
LIMIT 100
""
using
result = sqlutil.get(query, db=db, host=host,
                     user=user, password=password, asDict=True)

gives:

Failed to convert input data into array
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/ioa/software/python/2.7.8/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/opt/ioa/software/python/2.7.8/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/home/rgm/soft/listdriven/WISE2DES/sqlutil.py", line 169, in __converter
    res=fromrecords(tups,dtype=dtype, intNullVal=intNullVal)
  File "/home/rgm/soft/listdriven/WISE2DES/sqlutil.py", line 149, in fromrecords
    _array[k] = tuple(convF(recList[k]))
TypeError: long() argument must be a string or a number, not 'NoneType'

Traceback (most recent call last):
  File "wsdb_test.py", line 275, in <module>
    user=user, password=password, asDict=True)
  File "/home/rgm/soft/listdriven/WISE2DES/sqlutil.py", line 252, in get
    raise Exception('Child thread failed')
Exception: Child thread failed

**Comment by segasai** [comment]
Thanks for the bug report. I've fixed it now in 71f1af36fecbc0570e9aceca2660fa00bb07275c

**Comment by segasai** [comment]
Richard, 

Apparently when fixing this bug, I've introduced another nasty one.
I.e. if returned data had nulls in integer columns, the code erroneously replaced zeros in integer columns by the null placeholder (-9999)
I fixed it in 
e278e8098d0dd26bf81c1db64ead4a64b32a04b2
